### ISSUE TITLE
iPad View

### ISSUE THREAD

**Issue by moh1122** [kazi-mifta/iOSPress#2]
Hello
Is there any way to open the view on iPad the same way it opens on iPhone.
On iPad its launching a black screen and the posts are on the left.
How to show all the posts at launch?

**Comment by kazi-mifta** [comment]
At the time of development this was the default behavior of the SwiftUI List Function. Still I will recheck if there is any way to view them on iPad the same way it does on iPhone. I will update the library accordingly.

**Comment by kazi-mifta** [comment]
Hey @moh1122, I have added the feature to view the same way as it does on iPhone.
